# Generated by Django 4.2 on 2023-05-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('product', '0009_alter_order_options_remove_order_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='orders', to='vendor.vendor'),
        ),
    ]
