# Generated by Django 4.2 on 2023-05-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_order_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendors',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_paid',
        ),
    ]
