# Generated by Django 4.2 on 2023-05-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_order_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
